### ISSUE TITLE
Support for SANs section

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-ssl#117]
It would be nice to have support for [Subject Alternative Names](https://en.wikipedia.org/wiki/Subject_Alternative_Name) (SANs) sections in certificates.  TWIUI these are used to include metadata properties that denote the issuer of the certificate.

An example use case for this feature is Sam's Alexa Web Service implementation in Prolog: https://github.com/PlayingWithProlog/alexa/issues/2

**Comment by Anniepoo** [comment]
Glad forward progress happening on this!  i think Alexa's a great use case for Prolog. Let's support it.

**Comment by thetrime** [comment]
This is possible with #140 via certificate_san/2. There are potentially some downsides with #140 that need to be worked through first, though.

**Comment by thetrime** [comment]
I think with #140 merged this is now closed. You can get a list of the SANs on a certificate using certificate_field(Certificate, sans(SANs))
