### ISSUE TITLE
Please verify Windows build for 7.6

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-ssl#121]
Jan Burse has reported the following error on Windows with 7.6.0-rc1:

<pre>
?- use_module(library(http/http_ssl_plugin)).
<b>ERROR: c:/program files/swipl/library/crypto.pl:68:</b>
        c:/program files/swipl/library/crypto.pl:68: Initialization goal raised exception:
        '$open_shared_object'/3: Das angegebene Modul wurde nicht gefunden.
</pre>

@JanWielemaker, could you please verify the SSL build on Windows before releasing 7.6?

The above error may mean that `crypto4pl.obj` is missing, maybe?

The test cases in `test_ssl.pl` should all pass on this platform.

Thank you very much!

**Comment by JanWielemaker** [comment]
Thanks for noting.  It was building the interface against 1.1, but included the SSL DLLs for 1.02 ...  Pushed a fix that should first come up in the development daily versions.  Then in 7.6.0-rc2
