### ISSUE TITLE
Exchanging SSL context breaks HTTP timeout

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-ssl#127]
In the `packages/ssl` directory, let `https_server.pl` consist of the following code:

<pre>
:- use_module(library(http/thread_httpd)).
:- use_module(library(http/http_dispatch)).
:- use_module(library(http/http_unix_daemon)).

:- http_handler(/, handle_request, []).

handle_request(_Request) :-
    format("Content-type: text/plain~n~n"),
    format("Hello!").
</pre>

We can launch an HTTPS server on port 4090 as follows:

<pre>
$ p=etc/server; swipl https_server.pl --https --keyfile=$p/server-key.pem --certfile=$p/server-cert.pem --password=apenoot1 --interactive --port=4090  --timeout=0.1
</pre>

We can connect to the server as follows:

<pre>
$ openssl s_client -connect localhost:4090
</pre>

Note that the connection **terminates** almost instantly, due to the short timeout of 0.1s.

We now append the following clause to `https_server.pl`:

<pre>
http:ssl_server_open_client_hook(_SSL0, SSL, _Options) :-
        ssl_context(server, SSL,
                    [certificate_file('etc/server/server-cert.pem'),
                     key_file('etc/server/server-key.pem'),
                     password(apenoot1)]).
</pre>

This defines a *hook* so that a new SSL context is created on the fly for new client connections.

When we recompile the server (`?- make.`) and then connect again with:

<pre>
$ openssl s_client -connect localhost:4090
</pre>

Then **no timeout** is observable. This is completely unexpected, because this only changes the SSL context and should not affect the other connection parameters at all.

This is a **major** issue for sites that use this hook to *dynamically* update certificates while the HTTPS server keeps running: It means that SSL connections may linger indefinitely until the server runs out of file descriptors. Please have a look. Thank you!

**Comment by JanWielemaker** [comment]
If you add `close_parent(true)`, it works fine.  Figured this out from the non-hooked case.  All in all I'm not convinced the whole thing works.  Does this really create a new SSL instance for each connection?  My first reading of the code doesn't make this obvious to me.  You've been involved in this hook AFAIK ...

Needs testing, surely fixing the documentation and possibly more.  Please share what you know/find about this.

**Comment by JanWielemaker** [comment]
Oh, the reason is simple.  The timeout is set on the wire stream.   This nicely times out, causing an error/timeout in the unencrypted stream.  Now the unencrypted stream is closed.  Without the `close_parent` though, the wire stream is not.   I guess the docs should state the the SSL context must have the close_parent attribute set.  As you indicate to have a look at this hook anyway I leave that to you.

**Comment by JanWielemaker** [comment]
Yes, better that documentation most people will miss ....  Closing
