### ISSUE TITLE
rsa_* en/de crypt and representations

### ISSUE THREAD

**Issue by JanWielemaker** [SWI-Prolog/packages-ssl#13]
The rsa_public_encrypt/3, etc. predicates basically crypt and decrypt byte arrays.  This works really bad for text.  I think we need an encoding argument that probably should default to `utf8`.  If you want the current behaviour, pass `octet`.

**Comment by thetrime** [comment]
I think you've already implemented this, correct?

**Comment by JanWielemaker** [comment]
Yes, I close this
