### ISSUE TITLE
Support System keychain in addition to the  System *root* keychain on macOS

### ISSUE THREAD

**Issue by thetrime** [SWI-Prolog/packages-ssl#137]
In later versions of macOS it is not permitted to add certificates to the system root keychain - this is effectively baked into the OS. Instead, you are supposed to add certificates you trust to the system (or user) keychain.

To facilitate this, I suggest we load certificates from both the root keychain *and* the system keychain.

**Comment by JanWielemaker** [comment]
Sounds like a good idea.  Can you do that?

**Comment by thetrime** [comment]
Yep. It just took me longer to make the PR than it took you to check your emails, it seems!

**Comment by thetrime** [comment]
Oops. I think I messed up the PR. I'll push another one
