### ISSUE TITLE
The default SSL plugin overrides the cacerts/1 option

### ISSUE THREAD

**Issue by thetrime** [SWI-Prolog/packages-ssl#148]
Recently I added a cacerts/1 option to the SSL context, but now I realise that the http_ssl_plugin always adds `cacert_file(system(root_certificates))` to the option list, and if the cacert_file attribute is set then we use that in preference to any other options. There's no way to turn off cacert_file/1 once it has been supplied.

Altogether, this seems a bit awkward. There are now 3 ways to set up trusted certificates;
1. Use the system store via cacert_file(system(root_certificates))
2. Use a nominated file via cacert_file(Filename)
3. Use a list of certificates via cacerts(+List).

I propose we merge these all together. cacerts/1 will now accept a list of terms, and:
1. If they are the term system(root_certificates) then include the root certificates in the context
2. If they are a term file(Filename) then include that filename in the context
3. If they are an X509 blob, then include that certificate in the context

We can deprecate (but continue to accept) the cacert_file/1 mechanism (which is probably quite deeply embedded in existing code now) but change the code so that if cacerts/1 AND cacert_file/1 are both supplied, then to trust both sources.

Does this seem reasonable?

**Comment by triska** [comment]
Yes. For (3), please use `certificate(Blob)` to clearly distinguish the cases via dedicated functors.

A clean representation allows sensible error processing, suitable extensions, and also facilitates static type checking for options.

**Comment by JanWielemaker** [comment]
Yes, `cacerts(ListOfSources)` sounds good to me.    I'm afraid we need to preserve compatibility though :(

**Comment by triska** [comment]
Regarding compatibility, my recommendation is to support a defaulty representation as an undocumented additional way to specify a certificate, if it is absolutely necessary. However, new code should only use a clean representation, and eventually, this should be the only supported way.

**Comment by thetrime** [comment]
One significant difference this change would make is that currently you can set a file via cacert(Filename) and change the file without restarting anything. For example, you can set it to cacert('./foo.pem') and then run your system for some time. You can then change foo.pem to a new file and all future SSL contexts will just use it. If we load the cert when we initialise the context the first time, then it's in memory and won't change if the file changes (there are other problems, too - using SSL_CTX_load_verify_locations presumably allows a lot more formats for the certificate than load_certificate does...)

**Comment by thetrime** [comment]
Actually, perhaps not - the documentation for SSL_CTX_load_verify_locations [SSL_CTX_load_verify_locations](https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_load_verify_locations.html) says that

> The CAfile is processed on execution of the SSL_CTX_load_verify_locations() function.

and further that

> If CAfile is not NULL, it points to a file of CA certificates in PEM format. The file can contain several CA certificates

So perhaps we can just load the file directly and assume it's in PEM format. The only fishhook is that we need to be able to load potentially multiple certificates from the one file

**Comment by thetrime** [comment]
Does anyone have any preference for using cacerts(+List) vs allowing multiple cacert(+Term) values in the options list? The first is probably more precise, but the second is easier to manage via a hook...

**Comment by JanWielemaker** [comment]
> Does anyone have any preference

Yes.  I want to arrive at options that are single valued and have unique names.  That allows for unambiguously managing options lists (remove an option,  merge two lists, etc.) and eventually allow using dicts as options everywhere, providing cleaner code with better performance.

**Comment by thetrime** [comment]
Ok. That's unambiguous, at least. The code is almost done - I'll push the branch for review in a moment

**Comment by thetrime** [comment]
It looks like there's still a slight problem here. Suppose I want to add some options using http:open_options/2. I've added a clause that adds in some extra certificates, like this:
```
http:open_options(Parts, Options) :-
        memberchk(scheme(https), Parts),
        findall(certificate(Certificate),
                    adhoc_trusted_certificate(Certificate),
                    Certificates,
                    [system(root_certificates)]),
        Options = [cacerts(Certificates)]
```

However, if I run the code in http_open.pl to determine the final options:
```
http_open:parse_url_ex('https://www.google.com', Parts), 
findall(HostOptions, http:open_options(Parts, HostOptions), AllHostOptions),
foldl(http_open:merge_options_rev, AllHostOptions, [], Options).
```

I get
```
AllHostOptions = [[cacerts([system(root_certificates)])], [disable_ssl_methods([sslv23])], [cacerts([.... lots of certificates...., system(root_certificates)])]],
Options = [cacerts([system(root_certificates)]), disable_ssl_methods([sslv23])].
```

It's not possible to override the default value set in http_ssl_plugin.pl, in other words. 
Why does the hook fold in reverse?

**Comment by JanWielemaker** [comment]
Seems broken.   Surely, user options should overrule defaults.   Given the list approach of cacert option and the backward compatibility we  need something that knows more about the semantics and relation between the options to merge them the  proper way.   Please go ahead.

**Comment by thetrime** [comment]
Hmm. The strange thing is that you explicitly turned it around in 
https://github.com/SWI-Prolog/packages-http/commit/2e88db9f6dca069f851c69cdcc537528c99c0396
with a comment saying you were also solving this exact problem...

**Comment by JanWielemaker** [comment]
The C code of your patch looks fine.   The problem is that merge_options/3 is not ok for options that must be combined rather than replacing the old value with a new one.    In this case it is all not that clear what must happen.   If the user specifies certificates in the explicit options, should these be added to the ones provided by the implicit options or should they replace the implicit certifications?   I'm tempted to argue for replacing.   The current behavior is a strange mixture.  If you use the same option the older option value is replaced and if you use a different option it is added to the accepted certificates.   This is lost when using a single option, which is probably a good thing.

For short, I think I propose for http_open/3 to translate the certificate options of the hook to cacerts option and keep the merge as is.   With proper documentation this at least makes it clear what happens.  This is not compatible, but the current situation is a mess anyway.

**Comment by thetrime** [comment]
Perhaps we could add a new hook for http_open - rather than having http:open_options we have https:ca_certificate/1, and find all solutions to that? If you want to override the existing behaviour, you can then define
```
ca_certificate(MyCertificate):-   !, ....., 
```

or
```
ca_certificate(system(root_certificates)).
ca_certificate(MyCertificate):-   !, ....., 
```

and the default in the http_ssl module would be just the single clause
```
ca_certificate(system(root_certificates)).
```

How does that strike you? (Aside from incompatible with existing code. I guess we could add some kind of mapping rule that calls http:open_options, gets out the cacert_file/1 term and calls member/2 on it to enumerate the solutions....)

**Comment by JanWielemaker** [comment]
Hmm.  I think there are several issues with that.  The most important is that overruling using a ! in a multifile predicate is shaky at best because the clause ordering is poorly defined.    I think a cacerts option that replaces older options is not compatible but otherwise an improvement as it forces you to carefully consider what to accept

**Comment by thetrime** [comment]
I see your point, but I'm not sure what we can do instead. Suppose that we want to define a hook so that for a specific URL we only accept a specific certificate as the CA. We define our multifile hook and add the CA we want.... but then the 'default' one (system CA) gets added by the hook in the http_ssl_plugin.pl file. There's no way to *remove* items from the list.

It seems that what we really want is something *like*
```
( setof(Certificates, ca_certificates(URLParts, Certificates), CertificatesList)
-> merge_certificate_lists(CertificatesList, AllCertificatesForURL)
; default_ca_list(AllCertificatesForURL)
)
```

That means you can override the default CA by just defining a hook that gives [] as the CA list in your application. It's still ugly, but at least it's *possible* to achieve pinning this way.

**Comment by JanWielemaker** [comment]
My view is simpler (and maybe wrong).  We map all old options to cacerts(+List) to provide some basic backward compatibility (we could remove support for the old options from the C core).   Now options override.  So, if we want a specific CA for a url we can pass that as option the http_open/3 and get the desired result (no default CAs).

There is one _but_.  The http ssl plugin provides the url-independent `system(root_certificates)`.   If now we add a clause for `http:open_options/2` to define a specific CA for a specific URL this may or may not work depending on the order of the (multifile clauses).   Ideally we would have a more specific rule overruling a more general rule, but I do not see how to achieve that in a reasonable way.  

One way out might be to remove `system(root_certificates)` from the http SSL plugin and add it as fallback value later in the pipeline, i.e., as _default_ for the cacerts(List) option.   The last step makes a lot of sense to me anyway: regardless why you want an SSL connection it will by default use the system root certificates.

That of course leaves the issue that there can be multiple clauses for `http:open_options/2` that provide conflicting values for the same option.   I don't know whether this is a real issue.  If it is, I guess the most sensible solution is to extend the interface to give priorities to options.   I propose we skip that for now.  So, summary:

  - Remove handling of old certificate options (give a warning instead)
  - Remove http:open_options/2 from the HTTP ssl plugin
  - Convert old options to cacerts(List) for the opion list of http_open/2 and answers from
    http:open_options/2.
  - Handle a missing cacerts(List) option as default for `[system(root_certificates)]`
  - Keep merging options as is.  If it proves necessary at some point, use e.g. http_options/3,
    returning a priority that defines which is kept.

Does that make sense?

**Comment by thetrime** [comment]
> * Remove handling of old certificate options (give a warning instead)
I'm a bit worried about the impact this might have on existing code. For now, I've written some code to use cacert_file/1 to update the cacerts/1 list. This is maybe a bit confusing, but I think it'll work for existing code.

> * Remove http:open_options/2 from the HTTP ssl plugin
OK

> * Convert old options to cacerts(List) for the opion list of http_open/2 and answers from
>   http:open_options/2.
The way I implemented point 1 obviates this, but if you think it's worth breaking compatibility to tidy this up more aggressively, then I can have a go.

> * Handle a missing cacerts(List) option as default for `[system(root_certificates)]`
OK. That's basically what I was suggesting, but at a higher level. I like this approach better.

> * Keep merging options as is.  If it proves necessary at some point, use e.g. http_options/3,
>   returning a priority that defines which is kept.
Ok. That's fine by me. So long as it's *possible* to get the result I want, even if it's a bit awkward.

I'll push my code in a bit once I've given it a cursory test
