### ISSUE TITLE
HTTPS server does not close socket if negotiation fails

### ISSUE THREAD

**Issue by thetrime** [SWI-Prolog/packages-ssl#15]
in http_ssl_plugin.pl, thread_httpd:open_client_hook/5 opens the socket and does ssl negotiation on it. If this raises an exception, the socket remains open, and some clients will just hang waiting for the response that never comes.

**Comment by thetrime** [comment]
*sigh* nevermind, this has also already been fixed!

**Comment by triska** [comment]
In fact, this wasn't fixed until much more recently (in 2e9c4e1f67f1e920505f2aa7ea23c52f51ae5b4f).

It should be fixed now! Please let me know if there are remaining issues with negotiations and exceptions. Thank you!
