### ISSUE TITLE
Please recreate the example certificates with longer key lengths

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-ssl#153]
As of Debian buster, 2048 bit or larger keys are required for RSA and DHE keys:

https://www.debian.org/releases/stable/amd64/release-notes/ch-information.en.html#openssl-defaults

Since the certificates that ship with this package use shorter keys, test cases fail with Debian buster and later.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/cannot-find-source-file-tipc-c-while-compiling-on-debian-10/2077/12

**Comment by JanWielemaker** [comment]
Verified Matt's changes on a VM running Buster.  Thanks all!  Closing.
