### ISSUE TITLE
RSA_SSLV23_PADDING removed in OpenSSL 3.x

### ISSUE THREAD

**Issue by jamesjer** [SWI-Prolog/packages-ssl#160]
The RSA_SSLV23_PADDING definition has been removed in OpenSSL 3.0, leading to packages-ssl build failures.  See https://github.com/openssl/openssl/issues/14216 for the reasons behind the removal.

**Comment by JanWielemaker** [comment]
Seems this is used by the Prolog library(crypto) for rsa_(private/public)_(en/de)crypt/4 if these predicates are used with the option `padding(sslv23)`.   If I read the above conversation correctly it is claimed that one should never use this.   I think this was added by @thetrime to example certificates, no?

Just putting `#ifdef RSA_SSLV23_PADDING` around the line containing it would only cause these predicates to raise an error when used with this specific padding option.   That is not likely to break many applications that use this library.

**Comment by jamesjer** [comment]
Thank you for the quick reply, @JanWielemaker .  The Fedora project is currently migrating all packages to OpenSSL, which is why this came up.  I will patch the sources as you suggest for now.  Thank you!

**Comment by JanWielemaker** [comment]
Thanks for the info.   Pushed 93f076f7ee308c5c2fa2edc7d55f5a43d0bd901f.    Worst case some very specific applications will stop working with an exception.   That seems better than failing to compile.
