### ISSUE TITLE
SSL server negotiates obsolete cipher

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-ssl#23]
When I use the `sslscan` utility to detect which ciphers may be negotiated with an SWI-Prolog HTTPS server, i.e.:

<pre>
$ sslscan localhost | grep -i accept
</pre>

I get a very short list of acceptable ciphers:

<pre>
    Accepted  TLSv1  256 bits  AES256-SHA
    Accepted  TLSv1  256 bits  CAMELLIA256-SHA
    Accepted  TLSv1  128 bits  AES128-SHA
    Accepted  TLSv1  128 bits  SEED-SHA
    Accepted  TLSv1  128 bits  CAMELLIA128-SHA
    Accepted  TLSv1  128 bits  RC4-SHA
    Accepted  TLSv1  128 bits  RC4-MD5
    Accepted  TLSv1  112 bits  DES-CBC3-SHA
    Accepted  TLSv1  56 bits   DES-CBC-SHA
</pre>

How can I enable more ciphers?

I have created the following self-contained test case that only depends on the SSL library. First, here is `create_certificate.sh` to create `server.key` and `server.crt`:

<pre>
#!/bin/bash

openssl genrsa -out server.key 2048
openssl req -new -key server.key -out server.csr
cp server.key server.key.org
openssl rsa -in server.key.org -out server.key
openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt
</pre>

Run this file in Bash, or use any other key and certificate.

Then, let `server.pl` consist of:
<pre>
:- use_module(library(ssl)).

run :-
        ssl_context(server, SSL, [key_file('server.key'),
                                  certificate_file('server.crt')
                                  ]),
        tcp_socket(Socket),
        tcp_bind(Socket, localhost:Port),
        format("listening on port: ~w\n", [Port]),
        tcp_listen(Socket, 5),
        tcp_open_socket(Socket, AcceptFd, _),
        repeat,
            tcp_accept(AcceptFd, Client, _PeerName),
            tcp_open_socket(Client, StreamPair),
            stream_pair(StreamPair, PlainRead, PlainWrite),
            catch(ssl_negotiate(SSL, PlainRead, PlainWrite, _Read, _Write),
                  _,
                  true),
            catch(close(StreamPair), _, true),
            false.
</pre>

Then run the server with:

    $ swipl -g run server.pl

It tells you on which port it listens.

Then run:

    $ sslscan localhost:<port> | grep -i acc

to see the very short list given above.

I have a [patch](https://github.com/triska/packages-ssl) that lets you prioritize the available ciphers using the `cipher_list(Atom)` option when creating an SSL&nbsp;context. However, the ciphers I would like to use are not even available in the above list of accepted ciphers.

**Comment by triska** [comment]
When I use `openssl` to test the exact same configuration with:

    $ openssl s_server -cert server.crt -key server.key

and then run:

    $ sslscan localhost:4433 | grep -i acce

I get **4 more** ciphers than with `library(ssl)`:
<pre>
ECDHE-RSA-AES256-SHA
ECDHE-RSA-AES128-SHA
ECDHE-RSA-RC4-SHA
ECDHE-RSA-DES-CBC3-SHA
</pre>

How can I enable these additional ciphers?

**Comment by chigley** [comment]
The problem can be explained by a lack of Diffie-Hellman parameters.

The first thing to note is that your test case can be improved, making OpenSSL's `s_server` outperform `library(ssl)` even further, by explicitly passing DH parameters of a suitable length to OpenSSL:

	$ openssl dhparam -out dhparam.pem 2048
	$ openssl s_server -cert server.crt -key server.key -dhparam dhparam.pem
	$ sslscan localhost:4433 | grep -i acce

OpenSSL now offers 9 (previously 4) more ciphers than `library(ssl)`:

	    Accepted  TLSv1  256 bits  ECDHE-RSA-AES256-SHA
	    Accepted  TLSv1  256 bits  DHE-RSA-AES256-SHA
	    Accepted  TLSv1  256 bits  DHE-RSA-CAMELLIA256-SHA
	    Accepted  TLSv1  128 bits  ECDHE-RSA-AES128-SHA
	    Accepted  TLSv1  128 bits  DHE-RSA-AES128-SHA
	    Accepted  TLSv1  128 bits  DHE-RSA-SEED-SHA
	    Accepted  TLSv1  128 bits  DHE-RSA-CAMELLIA128-SHA
	    Accepted  TLSv1  128 bits  ECDHE-RSA-RC4-SHA
	    Accepted  TLSv1  112 bits  ECDHE-RSA-DES-CBC3-SHA

`library(ssl)` is lacking support for ephemeral Diffie-Hellman due to a lack of parameters. For DHE ciphers, the parameters take the form of a field prime `p` and a generator `g`. For ECDHE ciphers, the parameter is a choice of curve.

For DHE ciphers to work, you need to call either `SSL_CTX_set_tmp_dh()` or `SSL_CTX_set_tmp_dh_callback()`. OpenSSL documentation for these can be found at https://www.openssl.org/docs/manmaster/ssl/SSL_CTX_set_tmp_dh.html. ECDHE- ciphers require a call to either `SSL_CTX_set_tmp_ecdh()` or `SSL_CTX_set_tmp_ecdh_callback()`. Note that, in more recent versions of OpenSSL, `SSL_CTX_set_dh_auto()` and `SSL_CTX_set_ecdh_auto()` exist.

A reasonable approach would be to ensure that default parameters are in place, whilst allowing the user to configure their own. `library(ssl)` could include its own defaults or make use of OpenSSL's. If going with the former option, `openssl dhparam -C <bits>` can be used to generate C code for use in conjunction with `SSL_CTX_set_tmp_dh()`, and `NID_X9_62_prime256v1` is a good default curve choice.

**Comment by triska** [comment]
Charlie, many thanks for looking into this!

This is extremely valuable information, and I really appreciate your analysis. To benefit all users, could you please take a look at #22 and make the needed parameters and&mdash;where applicable&mdash;good defaults available analogously with a suitable patch? The best way to contribute to SWI and its packages is to fork the repository you need, commit and push the patch to your fork, and then file a pull request. This will also preserve you as the author. 

Cui honorem honorem!

**Comment by thetrime** [comment]
chigley seems to know a lot more about this than I do, but I like Markus' approach - maybe we can use default parameters if none are provided and allow the user to specify them via ecdhe_curve/1 or dhparam/1 (though maybe we could make it a bit more general purpose by passing in either a stream or a term representing the DH parameters rather than requiring a filename?)

I'm happy to try and do this if chigley is too busy, but it's a waste of time for us both to do it. Any other takers?

**Comment by chigley** [comment]
As a minor tweak, I prefer `ecdh_curve/1` over `ecdhe_curve/1`.

Re. generalising dhparam from a filename to a stream, I can't think of a reason not to, although it's worth noting that most users will likely be used to passing a filename for this (e.g. Apache's `DHParameters` and nginx's `ssl_dhparam`).  Could we provide both options?

I'd like to contribute but it's not clear when I'll find time. I'll check back here and comment before committing any significant time to this but, until then, feel free to take it. If someone beats me to it then I'd be more than happy to offer advice on the OpenSSL side of things.

**Comment by triska** [comment]
I have added the `ecdh_curve/1` paramater in [https://github.com/triska/packages-ssl/commit/cf4eb8615a35a79cb91c13bcf89386f6fb87966d](https://github.com/triska/packages-ssl/commit/cf4eb8615a35a79cb91c13bcf89386f6fb87966d).

@chigley, could you please try my fork? It provides 2 new features: `cipher_list/1` and said `ecdh_curve/1`. If this works for you, I will file a pull request. This fixes the issue I am most interested in: Enabling ciphers that are not yet obsolete, and selecting the ciphers one wants to use.

I leave the implementation of the `dhparam_file/1` for later. In fact, @thetrime, I would greatly appreciate if you could add this. I agree with Charlie that reading from a file should definitely be supported, and if there is a good way to plug in a stream too, that would also be very nice.

Thank you all for working on this!

**Comment by thetrime** [comment]
Sure. I should have time some time this week

**Comment by triska** [comment]
OK, I think `ecdh_curve/1` and also `cipher_list/1` is working as intended. I have filed pull request #24. @JanWielemaker: please merge. @chigley: Could you please try these changes when you get around to it, and also review the code? If you have time, I also would greatly appreciate if you could look into #21. Many thanks!

**Comment by chigley** [comment]
Yes, I plan to test and review your changes as soon as I get a chance. I'll also have a read of #21.

**Comment by triska** [comment]
@chigley : I would like to simulate what you have done, i.e., use a 2048-bit key for DH. For this, I have applied the following patch against the *current* `master` branch:

<pre>
diff --git a/ssllib.c b/ssllib.c
index 61ca5da..7d38acf 100644
--- a/ssllib.c
+++ b/ssllib.c
@@ -1309,6 +1309,56 @@ ssl_init_verify_locations(PL_SSL *config)
 
 }
 
+/* The following keys were generated with:
+   $  openssl dhparam -C 2048
+   (OpenSSL 1.0.2g  1 Mar 2016)
+*/
+#ifndef HEADER_DH_H
+#include <openssl/dh.h>
+#endif
+DH *get_dh2048()
+	{
+	static unsigned char dh2048_p[]={
+		0xE8,0x55,0x68,0x87,0x2E,0x7A,0x9A,0x50,0xB9,0xA8,0x21,0x05,
+		0x96,0xEC,0x80,0x44,0x31,0x2D,0x38,0x6F,0x23,0xC8,0xE5,0xFB,
+		0x76,0xDB,0x53,0x01,0x51,0x41,0xA4,0xE4,0x85,0x3C,0xB2,0xBA,
+		0x1A,0x38,0xB4,0xA3,0x8E,0xA6,0x29,0xD6,0x3C,0x19,0x6E,0xC5,
+		0xC6,0x76,0xBB,0x77,0x0E,0x73,0x49,0x57,0x78,0x61,0x2A,0x45,
+		0xCD,0x1D,0x60,0xB2,0xA0,0xE9,0xEE,0x43,0xE8,0xEA,0xBC,0x60,
+		0xB7,0xC8,0xE7,0x43,0x78,0x54,0xB0,0x35,0x39,0xB7,0x2A,0x36,
+		0x5C,0xF1,0x00,0x5D,0x08,0x7C,0x97,0x0C,0x13,0x4D,0x86,0x41,
+		0xF4,0x8C,0xB6,0x43,0xF5,0xA8,0x74,0x3C,0xAF,0x2B,0x51,0xF2,
+		0xAE,0xB9,0xD6,0x18,0x13,0x09,0xE1,0x02,0xB1,0xFA,0xA3,0x40,
+		0x2D,0xC9,0xAB,0xD2,0x83,0x0E,0x5E,0xDB,0x23,0x32,0x02,0xE2,
+		0x2D,0x0F,0x8D,0xC5,0x47,0x9D,0xE0,0xBC,0x41,0x42,0xF4,0x0F,
+		0x1B,0xA4,0x22,0xD2,0x75,0xED,0x0C,0xA8,0x88,0x5B,0x09,0x8B,
+		0x57,0x5A,0xA8,0xD1,0xC9,0xB6,0x14,0xA4,0xDD,0x9F,0x1F,0x57,
+		0x06,0xC1,0xBA,0x6E,0xD0,0xB4,0x93,0xEA,0x46,0x5C,0x4E,0x54,
+		0x41,0x02,0x8F,0xD2,0x8D,0x3D,0x0A,0xAE,0x02,0xB8,0x7D,0x25,
+		0xFF,0x95,0xD3,0xB5,0xC6,0xD4,0x0B,0x6E,0x9D,0x7C,0x37,0x9C,
+		0xD3,0x44,0xAE,0x9E,0xAD,0x6F,0x10,0x71,0x55,0x4A,0x12,0x51,
+		0xB1,0x4E,0x81,0x1B,0x51,0xEB,0x5C,0xA1,0xF3,0x5C,0xA9,0x54,
+		0x16,0xFC,0x36,0x9B,0x61,0xFE,0xB2,0xDA,0x66,0x89,0x83,0x98,
+		0xA4,0xDF,0x31,0xAE,0x14,0x87,0x9C,0xFE,0x47,0x75,0x00,0xAE,
+		0x1F,0xA0,0x6B,0x7B,
+		};
+	static unsigned char dh2048_g[]={
+		0x02,
+		};
+	DH *dh;
+
+	if ((dh=DH_new()) == NULL) return(NULL);
+	dh->p=BN_bin2bn(dh2048_p,sizeof(dh2048_p),NULL);
+	dh->g=BN_bin2bn(dh2048_g,sizeof(dh2048_g),NULL);
+	if ((dh->p == NULL) || (dh->g == NULL))
+		{ DH_free(dh); return(NULL); }
+	return(dh);
+	}
+
+DH *tmp_dh_callback(SSL *s, int is_export, int keylength)
+{
+  return (keylength == 2048) ? get_dh2048() : NULL;
+}
 
 int
 ssl_config(PL_SSL *config, term_t options)
@@ -1347,6 +1397,8 @@ ssl_config(PL_SSL *config, term_t options)
     ssl_deb(1, "certificate installed successfully\n");
   }
 
+  SSL_CTX_set_tmp_dh_callback(config->pl_ssl_ctx, tmp_dh_callback);
+
   nid = OBJ_sn2nid(config->pl_ssl_ecdh_curve ? config->pl_ssl_ecdh_curve
 					     : "prime256v1");
   if ( !(ecdh = EC_KEY_new_by_curve_name(nid)) )
</pre>

This should now be analogous to what you have done and at least provide a suitable default. However, applying this patch does not change the list that the test server (see `server.pl`) above accepts! With openssl&nbsp;1.0.1k on Debian 8.1, I get (with and without the patch):
<pre>
$ sslscan localhost:39311 | grep -i acc
    Accepted  TLSv1  256 bits  ECDHE-RSA-AES256-SHA
    Accepted  TLSv1  256 bits  AES256-SHA
    Accepted  TLSv1  256 bits  CAMELLIA256-SHA
    Accepted  TLSv1  128 bits  ECDHE-RSA-AES128-SHA
    Accepted  TLSv1  128 bits  AES128-SHA
    Accepted  TLSv1  128 bits  SEED-SHA
    Accepted  TLSv1  128 bits  CAMELLIA128-SHA
    Accepted  TLSv1  128 bits  ECDHE-RSA-RC4-SHA
    Accepted  TLSv1  128 bits  RC4-SHA
    Accepted  TLSv1  128 bits  RC4-MD5
    Accepted  TLSv1  112 bits  ECDHE-RSA-DES-CBC3-SHA
    Accepted  TLSv1  112 bits  DES-CBC3-SHA
</pre>

and on OSX with openssl 1.0.2h, I get:

<pre>
Preferred TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA384       Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
Preferred TLSv1.1  256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
Preferred TLSv1.0  256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
Preferred SSLv3    256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
</pre>
(also with and without the patch).

Only when I produce a **1024**-bit key and include it analogously to the patch shown above, I get a significantly longer list of acceptable ciphers (shown for OSX):

<pre>
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA384       Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
<b>
Accepted  TLSv1.2  256 bits  DHE-RSA-AES256-GCM-SHA384     DHE 1024 bits
Accepted  TLSv1.2  256 bits  DHE-RSA-AES256-SHA256         DHE 1024 bits
Accepted  TLSv1.2  256 bits  DHE-RSA-AES256-SHA            DHE 1024 bits
... many more omitted
</b>
</pre>

Could you please explain how we can also enable these ciphers using a **2048**-bit key like you did? Alternatively, should we simply create and include a 1024-bit key (at least as default)? I doubt that this would be a good idea: I tried it, and the SSLLABS security assessment dropped from A- to B because most or even all ciphers that are then newly available are considered weak.

**Comment by FunctionAnalysis** [comment]
Just to hop in real quick, if performance won't be sacrificed too much I
suggest a 2048 as default.  While we're assuming users familiar with this,
most may not be aware of recommended key sizes.  If we can provide a bit
stronger crypto as default I think it would help everyone involved.  This
is just my opinion.

**Comment by triska** [comment]
@chigley: I got DH key exchange working thanks to your advice, thank you! Please see #27.

**Comment by triska** [comment]
This all works now. Thank you!
