### ISSUE TITLE
pem_password_hook/1 option is broken

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-ssl#30]
To see this, try in `packages/ssl` the following:

<pre>
$ swipl -g server server.pl
Returning password from server passwd hook
ERROR: Prolog initialisation failed:
<b>ERROR: SSL(06065064) EVP_DecryptFinal_ex: bad decrypt</b>
</pre>

This was broken by **1a11ca3734b54b6e9a89dd347d815799d32d6288**:

<pre>
diff --git a/ssl4pl.c b/ssl4pl.c
index 7c1f81f..14ef42f 100644
--- a/ssl4pl.c
+++ b/ssl4pl.c
@@ -1048,9 +1048,11 @@ pl_pem_passwd_hook(PL_SSL *config, char *buf, int size)
   if ( PL_call_predicate(NULL, PL_Q_PASS_EXCEPTION, pred, av) )
   { if ( PL_get_nchars(av+1, &len, &passwd, CVT_ALL) )
     { if ( len >= (unsigned int)size )
-       PL_warning("pem_passwd too long");
-      else
-       memcpy(buf, passwd, len);
+      { PL_warning("pem_passwd too long");
+      } else
+      { memcpy(buf, passwd, len);
+       passwd = buf;
+      }
     } else
       PL_warning("pem_passwd_hook returned wrong type");
   }
</pre>

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with 81d0219f009ec7073c19d742aa00ad2b5bcc6841
