### ISSUE TITLE
HTML table formatting

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-ssl#36]
When I do `make doc`, I obtain `ssl.html` which is correctly formatted.

In contrast, the table in Section 2 lacks a `|` at the right border:

[http://eu.swi-prolog.org/pldoc/doc_for?object=section(%27packages/ssl.html%27)](http://eu.swi-prolog.org/pldoc/doc_for?object=section(%27packages/ssl.html%27))

**Comment by JanWielemaker** [comment]
Looks ok to me now.

**Comment by triska** [comment]
It looks OK for me in Firefox, but not with the latest Chrome (tested on OSX and Debian).

**Comment by JanWielemaker** [comment]
It pretty much defines the border as it looks like in FF (2 pixels solid black).  If it doesn't work, complain with Chrome ...
