### ISSUE TITLE
copy_stream_data/2 yields I/O error with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-ssl#53]
To reproduce, please compile and link with OpenSSL 1.1.0 (see #51 for more information), and start SWI-Prolog with:

<pre>
$ swipl -f none
</pre>

Then, use:

<pre>
?- <b>use_module(library(http/http_open)),
   http_open('https://www.metalevel.at', In, []),
   copy_stream_data(In, current_output).</b>
</pre>

**Result**:

The data is shown exactly as expected, followed by:

<pre>
<b>ERROR: copy_stream_data/2: I/O error in read on stream <stream>(0x2718700) (Success)</b>
</pre>

After that, normal toplevel interaction is resumed.

**Comment by JanWielemaker** [comment]
Works fine with 1.0.2g.   The error suggests something goes wrong, making the read handler return `-1`, but errno is not set and no error is registered with the stream (Sseterr()).

**Comment by triska** [comment]
Please try it with 1.1.0: This may be related to the new way the BIO methods are created with the OpenSSL&nbsp;1.1.0 API.

**Comment by triska** [comment]
This is due to a change in the behaviour of OpenSSL that is currently being discussed in:

https://github.com/openssl/openssl/issues/1903

In short, `EOF` can currently lead to `SSL_read()` returning `-1` when it previously returned&nbsp;`0`.

The correct fix will depend on how OpenSSL resolves this issue.

Fixing this issue portably will likely require a case distinction between the already released `1.1.0c` as well as earlier and possibly later versions.

**Comment by triska** [comment]
#60 addresses this portably, for `1.1.0c` and also later versions.

**Comment by triska** [comment]
Corrected with b415e1e588e3ec12fcaf30e00a66efe8d1914aeb.
