### ISSUE TITLE
unify_hash should use portable structures in 2 places

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-ssl#59]
In `ssl4pl.c`, there are currently two places marked `TODO`:

- `unify_hash(hash, palg->algorithm, i2d_X509_CRL_INFO_wrapper, crl)`
- `unify_hash(hash, palg->algorithm, i2d_X509_CINF_wrapper, data)`

The reason for this is that the members which are used as the last arguments in OpenSSL versions prior to&nbsp;1.1.0 (`crl->crl` and `data->cert_info`, respectively) are no longer accessible with more recent versions of&nbsp;OpenSSL, so I have used `crl` and `data` instead.

@keriharris: Please have a look: Is this a valid choice, and can we use this also in earlier OpenSSL versions? Alternatively, is there any other part of these structures we can uniformly use in all (sufficiently recent) versions of OpenSSL, and thus simplify the code? Thank you!

**Comment by JanWielemaker** [comment]
Most of the ssl binding as it looks now is the work of @thetrime.  @keriharris and me deal more with portability issues.
