### ISSUE TITLE
Suggestion: library(crypto)

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-ssl#76]
Currently, `library(ssl)` supplies both

  1.  **connection-oriented** predicates that are very heavily used in web servers and clients
  2. **cryptographic** and **authenticity**-related predicates that can be sensibly used in isolation, and cater mostly to more specialized use cases.

In the first group, the most notable are:

  - `ssl_context/3`
  - `ssl_negotiate/5`
  - `ssl_session/2`

as well as some predicates retained for backwards compatibility with the deprecated interface (`ssl_init/3` etc.).

In the second group, we have:

  - `evp_decrypt/6`
  - `evp_encrypt/6`
  - `load_certificate/2`
  - `load_private_key/3`
  - `load_public_key/2`
  - `load_crl/2`
  - `rsa_private_decrypt/3`
  - `rsa_private_encrypt/3`
  - `rsa_public_decrypt/3`
  - `rsa_public_encrypt/3`
  - `rsa_private_decrypt/4`
  - `rsa_private_encrypt/4`
  - `rsa_public_decrypt/4`
  - `rsa_public_encrypt/4`
  - `rsa_sign/4`
  - `rsa_verify/4`

These predicates *may* be used in the context of a connection, and also make sense in isolation. It makes sense that loading `library(ssl)` *also* provides these predicates. However, there are several more predicates that could be provided by adding suitable bindings to the `libcrypto` functions of&nbsp;OpenSSL. For example:

  - `md5_hash/2`
  - `sha1_hash/2`

etc., with the prospect of many more in the future for special purposes.

Adding all these predicates to the "core" `library(ssl)` documentation makes it rather unwieldy.

I suggest to move predicates of the second category to the new `library(crypto)`, as a new part of the `ssl` package, and include a pointer from `library(ssl)` to these predicates. What do you think?

**Comment by JanWielemaker** [comment]
Matt and I had that discussion before.  I don't think it is worth the trouble.  All in all the stuff depends on OpenSSL (or a variant thereof).  If we make two Prolog libraries, they also need to depend on two
shared objects, which means we should nicely split the C code.  There is probably quite some shared
C stuff between both, mostly complicating this.

If documentation is the reason we can use the same trick as for clp(fd) to structure it.    Not sure we
need that much documentation though.  Basically these libraries are used by the few people understanding a little about cryptography to implement high level stuff such as the HTTPS plugin,
XML signatures, etc.

**Comment by triska** [comment]
Yes, I suggest **splitting the C code**.

I have looked at the code, and the parts I mention above can be cleanly separated because the functions in the second group **do not need an SSL&nbsp;context**.

To show you what I mean, I have isolated most of the cryptographic functions in the `libcrypto` branch:

https://github.com/triska/packages-ssl/tree/libcrypto

Please see [**cryptolib.c**](https://github.com/triska/packages-ssl/blob/libcrypto/cryptolib.c) for how this could look like.

All these functions can be *removed* from `ssl4pl.c`, decoupling these parts and making it easier to use LibreSSL for *either* of these parts in isolation.

If you agree that this separation is good, I will continue with it, removing (in my branch) these functions from  `ssl4pl.c`.

**Comment by JanWielemaker** [comment]
Your  cryptolib.c still contains ssl stuff and the end.  Is that just incomplete splitting?  Anyway, what
will we end up with?

  - library(ssl)
    - ssl4pl.so
      - libssl.so
  - library(crypto)
    - crypto4pl.so
      - libcrypto.so

If that is what we end up with and there is little overlap in ssl4pl.so and crypto4pl.so, I'm happy.
Note that if it is just about having less in one C file, I'm also happy to have two that create a single
.so file.

**Comment by triska** [comment]
Yes, this is only to show the general outline.

And yes, this structure would make a lot of sense in my view, and I anticipate only little overlap between the two files.

So, I will continue with this, and leave this issue open until this is done.

**Comment by triska** [comment]
In pull request #77, the dependencies are:

  - `library(ssl)`
    - `ssl4pl.so`
      - `ssllib.so`
  - `library(crypto)`
    - `crypto4pl.so`
      - `ssllib.so`

`ssllib.so` provides a functionality (like debugging, compatibility macros, OpenSSL&nbsp;initialization etc.) that both high-level libraries depend on. It *mostly* serves `ssl4pl.so` though. If really necessary, I can reorganize this slightly by moving functionality that is needed by *both* `library(crypto)` and `library(ssl)` to a new shared library. However, there is so little overlap that creating a further source file is not worth&nbsp;it in my opinion. Structurally, the opposite may be more justified: I could move a lot of the functionality from `ssllib.c` *directly* to `ssl4pl.c`, and avoid one layer of indirection in many cases, leaving only the common dependencies in `ssllib.c`.

Still, at least for now, I have mostly retained the current structure, moved a few compatibility functions from `ssl4pl.c` to `ssllib.c` to make them generally usable, and moved all encryption/decryption and authentication predicates to the new `library(crypto)`. The certificate and key *loading* predicates remain in `library(ssl)`, since they are needed during hooks and other parts of the&nbsp;code when negotiating connections.

In addition, I have added OpenSSL-based `md5_hash/3` to `library(crypto)` as the first new&nbsp;binding that has now found a natural&nbsp;home.

Enjoy!

**Comment by JanWielemaker** [comment]
I can imagine the enthusiasm.  This however is precisely why I wasn't that happy about this split.  If
you load either you get libssl.so in as well, which in turn loads libcrypto.so.  That is where most of
the resources go.  So, the split has practically zero value for minimizing the footprint if you want only half.  It complicates redistribution (what do I need to include).  It breaks compatibility.  Both are not dramatic and may be justified by a clearer conceptual split.  IMHO it isn't worth the trouble.  As you seem to want it really much I'll go along.

P.s. we already have two MD5, one in library(semweb/rdf_db) (deprecated) and one in the clib
package.  I do think that has value as it it really small and has no external dependencies.

**Comment by triska** [comment]
I cannot regard "I'll go along" as a satisfying conclusion of this issue. I want users to have a benefit from this separation, and would like to find a solution that you fully support and endorse!

How about #78 ? This completely **disentagles**`library(crypto)` from `libssl`, so that we now have the structure:

 - library(ssl)
   - ssl4pl.so
      - ssllib.so
 - library(crypto)
   - crypto4pl.so
      - cryptolib.so

Thus, you can use the cryptographic predicates without loading the full SSL library.

The introduction of [`library(md5)`](http://eu.swi-prolog.org/pldoc/man?section=md5) states:

> This is a rather short-term solution waiting for a more general interface to the `libcrypto` functions of OpenSSL.

I wonder what is or was meant by this, if not exactly this functionality that is now available?

**Comment by JanWielemaker** [comment]
#78 makes it a little more promising.   Still libssl.so depends on libcrypto.so, which is an order of magnitude larger.  So, in any case if you want either or both ssl or crypto you load almost all the resources. 

> I wonder what is or was meant by this, if not exactly this functionality that is now available?

Not sure.  For some stuff OpenSSL can select algorithms by name.  Possibly this could provide a generic predicate that accesses all hash algorithms known to OpenSSL.  That can be useful for signature handling where the hash algorithm is specified in the document. I don't think we want OpenSSL for the common secure hashes such as MD5 and SHA.  There are nice dedicated libraries that only require a couple of Kbytes and have no dependencies.  I'd rather use those if I need a secure hash in a context that is not tightly related to stuff for which OpenSSL is needed anyway.

**Comment by triska** [comment]
OK, I must say that I am a bit perplexed by this situation: I found past discussions that suggest precisely such a separation, and all received enthusiastic or at least welcoming feedback, also by you. Now, it almost looks like this is a change that is not wanted or needed.

I'm in favour of this separation: In my view, `library(crypto)` can bundle interesting functionality that is not needed by most users, but very important to some, and makes it clear that that there is a dedicated library for cryptographic functionality, and that further extensions are welcome. In addition, I think this separation will simplify a port to LibreSSL or other libraries, since one can handle one library at a time.

However, I really do not want to push for a change that you only tolerate, so please take your time to consider this, and revert the commits if you think that would be better. Thank&nbsp;you!

**Comment by JanWielemaker** [comment]
As I said, the split is conceptually better.  It doesn't save significant resources in any scenario I see.   So, to me, it is not a significant improvement.    It is a little improvement though, so I think it is justified to keep it.

**Comment by triska** [comment]
Good, than I am closing this issue with the words "better a little improvement than none".

Thank you for reviewing these changes.
