### ISSUE TITLE
Host validation

### ISSUE THREAD

**Issue by JanWielemaker** [SWI-Prolog/packages-ssl#8]
If provided (recent versions of OpenSSL), we should do host validation using X509_check_host()

**Comment by thetrime** [comment]
http://wiki.openssl.org/index.php/Hostname_validation has some info on this, including how to do it on version of OpenSSL < 1.0.2 (which is only a month old, after all). It also says that if a verify-callback is provided and returns success, it is assumed that the hostname check is handled in the callback, but that you can check the results of the verification by using SSL_get_verify_status(). This sounds like a great trap for new players!

**Comment by thetrime** [comment]
This has been finished in a branch host-verify. In addition to host verification, I've added unit tests for 24 different certificate validation/rejection cases (2 of which are currently commented out because we have not yet determined how to proceed with CRLs)

**Comment by thetrime** [comment]
I think this is now complete and merged into master?
