### ISSUE TITLE
Simplify library structure

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-ssl#82]
We currently have the following library structure:

- ssl4pl.c
  - ssllib.c
    - cryptolib.c
- crypto4pl.c
  - cryptolib.c

I don't see the point of `ssllib.c` in this structure, and suggest merging it with `ssl4pl.c`. Currently we have a lot of indirect interactions via:

ssl4pl.c &rightarrow; ssllib.c &rightarrow; OpenSSL

I would see the point in this if *either* or both of the following were true:

- the data structures of ssllib.c are completely **opaque**, so that the `ssl_set_...` functions are the *only* way to change the main structure (`PL_SSL`) that `ssllib.h` exposes.
- ssllib.c is completely independent from the SWI Prolog functions.

Currently, *neither* of these conditions are met. As a consequence, the setters mainly ensure that configuring the SSL&nbsp;context is more tedious than it could be, by first setting `PL_SSL` and then relying on ssllib.c to configure the actual OpenSSL data structures. They do not protect the `PL_SSL` data structures from direct access, and further ssllib.c still depends on specifics of SWI-Prolog, like invoking Prolog predicates.

In the 7.5 development line, I will simplify this structure.

@thetrime: Please comment if you have any opinion on this. Thank you!

**Comment by JanWielemaker** [comment]
I agree.  This was the work of the original author of the SSL binding, Jan van der Steen.  I guess this separation made sense to him to create an understandable abstraction of OpenSSL he could reuse in other projects.  It doesn't make much sense to me and the separation isn't that strict anyway,

Without putting pressure, I'm more in favour doing this *before* the 7.4.x split.  We (you :) have made so many structural that one more or less is probably not going to make the library less stable.   Having a close related source simplifies cherry-picking security patches from 7.5 to 7.4.

**Comment by triska** [comment]
Very well, I will finish this for 7.4, which is much more preferable also to me!

**Comment by triska** [comment]
Done!
