### ISSUE TITLE
Deal with CRL

### ISSUE THREAD

**Issue by JanWielemaker** [SWI-Prolog/packages-ssl#9]
We need some way to deal with CRL.

**Comment by thetrime** [comment]
It looks to be the case that we cannot rely on the OS to do this like we could with the CAs. For one thing, even if we did have access to an OS-level CRL cache, unlike the root CAs which only tend to change on OS upgrade, the CRL can change at any time. 

This seems like a fairly big task: Somehow we have to spawn a daemon that can periodically refresh CRLs for certificates we trust as CAs. This includes any supplied by the user. Some of these CRLs can be very large and slow to download - caching across sessions will be critical to get tolerable performance. This raises a whole lot of questions:
1) Where can we store the CRLs between sessions? In the user's swipl-home directory?
2) What format should we store them in? We need a quick lookup based on the URL. Perhaps a prolog file containing a number of facts, or we could store them in a directory with files named for the URLs?
3) What do we do if we don't have a CRL for a certificate we are trying to verify? Do we block and try to retrieve it? What if we cannot? (For example, the CRL might have a URL that is no longer valid, or might have garbage in the field, or the user might not have network access outside of a LAN, or....)
4) CRLs can be distributed by any well-formed URL. This is typically either HTTP (which is well-supported in SWI-Prolog) or LDAP (which I suspect is not supported directly in SWI-Prolog), but could in theory be any other protocol too, I think.
5) Do we want to expose the interface for manipulating these CRLs to the user so they can use them in their own certificate verification callbacks?
6) The OpenSSL internal verifier will only use CRLs already present in the store when trying to verify a certificate. How do we know which CRLs we might need until we've opened the connection and tried to verify the peer?
